### ISSUE TITLE
setup_functions.sh for Windows OS

### ISSUE THREAD

**Issue by kyokonishito** [IBM/Predictive-Industrial-Visual-Analysis#16]
Is it possible to create setup_functions.sh for Windows OS?

setup_functions.sh can not run with Windows OS.
It is very helpful for developers if there is setup_functions.bat for Windows OS.

Thank you.

**Comment by raheelzubairy** [comment]
@kyokonishito Thanks for the suggestion
Currently, there are alternatives for running shell scripts on windows through different tools such as: [gitbash]( https://epsil.github.io/blog/2016/04/20/), [Cygwin](https://www.cygwin.com/), [win-bash](http://win-bash.sourceforge.net/)
