### ISSUE TITLE
IBM Cloud UI change 

### ISSUE THREAD

**Issue by hisunah** [IBM/Predictive-Industrial-Visual-Analysis#17]
IBM Cloud Functions UI had been changed from what has described in README. There's no ``Manage`` and ``Develop`` under IBM Cloud Functions anymore.  Please update the description. 

#### Explore IBM Cloud Functions

In IBM Cloud, look for ``Functions`` in ``Catalog``

There you will see a UI to ``Manage`` and ``Monitor`` the service. In addition, it has information for ``Getting Started`` and even ``Develop`` actions.

<p align="center">
  <img width="800"  src="readme_images\cloud_functions_scrnshot.png">
</p>

**Comment by raheelzubairy** [comment]
Thanks @hisunah 
Updated with PR #20
