### ISSUE TITLE
Help with cloudant configuration

### ISSUE THREAD

**Issue by monikagupta78** [IBM/Predictive-Industrial-Visual-Analysis#26]
I am not able to setup these details for cloudant, hence getting below error when running script setup_functions :

Adding VCAP_SERVICES as parameter
ok: updated package image_db
Binding cloudant
error: Binding creation failed: The request content was malformed:
entity name malformed (code 91b69c508ee19fc54f4cf7ee45a0e9fa)
Creating trigger
ok: deleted trigger image_db-cloudant-update-trigger
error: Unable to create trigger 'image_db-cloudant-update-trigger': Unable to configure feed '/_/image_db-cloudant/changes': The requested resource does not exist. (code bb3ae432b8e5f1cafc1580b83b351bea)

Need help in setting credentials (may be use no credentials/ or using API key) for cloudant service  and update setup_functions script accordingly?

#From cloudant NoSQL database
CLOUDANT_USERNAME=
CLOUDANT_PASSWORD=

**Comment by raheelzubairy** [comment]
@monikagupta78 You can get the credentials by choosing the `Service Credentials` from the menu on the left, when you open your `Cloudant service`.  Then place these credentials in the `.env` file

<img width="1394" alt="screen shot 2018-08-20 at 2 25 27 pm" src="https://user-images.githubusercontent.com/27243319/44361931-1386b100-a485-11e8-9ddf-9d493bd55062.png">
